# Generated by Django 6.0.2 on 2026-06-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kingart', '0006_alter_blog_image_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
    ]
